# Generated by Django 5.0.6 on 2024-05-20 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="expiry",
            field=models.PositiveIntegerField(
                default=1716181753,
                validators=[django.core.validators.MaxValueValidator(99999999999)],
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="t_type",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
