# Generated by Django 5.0.6 on 2024-05-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="users",
        ),
    ]
