# Generated by Django 5.0.6 on 2024-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="contact",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
